const USB_DETECTOR_WS_URL = "ws://localhost:12345"
const SESSION_KEY = "workstation_fingerprint"

// Must match FINGERPRINT_VERSION in backend/machine_fingerprint.py.
// Bump in both places whenever the hash inputs change so cached fingerprints
// from older algorithms are treated as stale and re-fetched.
const EXPECTED_FINGERPRINT_VERSION = "v2"

export interface MachineFingerprint {
  machine_id: string
  components: Record<string, string>
}

/**
 * Synchronously read the cached machine_id, but only if it was generated by
 * the current algorithm version. Returns "" if missing, malformed, or stale.
 * Use this from request hot paths (e.g. setting the X-Machine-Id header)
 * where we shouldn't accidentally send a hash from a previous algorithm.
 */
export function getCachedMachineId(): string {
  const stored = sessionStorage.getItem(SESSION_KEY)
  if (!stored) return ""
  try {
    const parsed = JSON.parse(stored) as MachineFingerprint
    if (parsed?.components?.fingerprint_version !== EXPECTED_FINGERPRINT_VERSION) {
      return ""
    }
    return parsed.machine_id || ""
  } catch {
    return ""
  }
}

/**
 * Get the workstation fingerprint from usb_detector.py.
 *
 * 1. Returns cached value from sessionStorage if available.
 * 2. Otherwise opens a temporary WebSocket to usb_detector.py,
 *    authenticates, receives the MACHINE_FINGERPRINT event,
 *    caches it, and closes the connection.
 *
 * Throws if usb_detector.py is not running or the connection fails.
 */
export function fetchWorkstationFingerprint(): Promise<MachineFingerprint> {
  // Check cache first — but only honour it if the fingerprint was generated
  // by the current algorithm version. Otherwise fall through and re-fetch
  // from usb_detector.py so we never bind/verify with a stale hash.
  const stored = sessionStorage.getItem(SESSION_KEY)
  if (stored) {
    try {
      const parsed = JSON.parse(stored) as MachineFingerprint
      if (parsed?.components?.fingerprint_version === EXPECTED_FINGERPRINT_VERSION) {
        return Promise.resolve(parsed)
      }
      // Stale algorithm — drop the cache and fall through to a fresh fetch.
      sessionStorage.removeItem(SESSION_KEY)
    } catch {
      sessionStorage.removeItem(SESSION_KEY)
    }
  }

  const userInfo = JSON.parse(sessionStorage.getItem("user") || "{}")
  if (!userInfo?.authToken) {
    return Promise.reject(new Error("Not authenticated"))
  }

  return new Promise((resolve, reject) => {
    let settled = false
    const ws = new WebSocket(USB_DETECTOR_WS_URL)

    const timeout = setTimeout(() => {
      if (!settled) {
        settled = true
        ws.close()
        reject(new Error("USB detector is not running. Start usb_detector.py on the target workstation first."))
      }
    }, 5000)

    ws.onopen = () => {
      ws.send(JSON.stringify({ type: "auth", token: userInfo.authToken }))
    }

    ws.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data)
        if (data.event === "MACHINE_FINGERPRINT") {
          const fingerprint: MachineFingerprint = {
            machine_id: data.machine_id,
            components: data.components,
          }
          sessionStorage.setItem(SESSION_KEY, JSON.stringify(fingerprint))
          if (!settled) {
            settled = true
            clearTimeout(timeout)
            ws.close()
            resolve(fingerprint)
          }
        }
      } catch {
        // Ignore non-JSON or unrelated messages
      }
    }

    ws.onerror = () => {
      if (!settled) {
        settled = true
        clearTimeout(timeout)
        reject(new Error("USB detector is not running. Start usb_detector.py on the target workstation first."))
      }
    }

    ws.onclose = () => {
      if (!settled) {
        settled = true
        clearTimeout(timeout)
        reject(new Error("USB detector connection closed before fingerprint was received."))
      }
    }
  })
}
