"""Add pending_pin_verification_serial to AuthenticationSession

Revision ID: 031c20414986
Revises: 29afec349775
Create Date: 2025-07-31 13:32:15.546728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031c20414986'
down_revision = '29afec349775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentication_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_pin_verification_serial', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentication_session', schema=None) as batch_op:
        batch_op.drop_column('pending_pin_verification_serial')

    # ### end Alembic commands ###
