"""Remove model column and rename type to device_type in SecurityKey

Revision ID: 29afec349775
Revises: dd01cffff099
Create Date: 2025-07-24 16:55:26.332924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29afec349775'
down_revision = 'dd01cffff099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_key', schema=None) as batch_op:
        batch_op.alter_column('type', new_column_name='device_type', existing_type=sa.String(length=100), nullable=True)
        batch_op.drop_column('model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('device_type', new_column_name='type', existing_type=sa.String(length=100), nullable=True)

    # ### end Alembic commands ###
