"""simplify_app_settings_to_three_fields

Revision ID: 29c5aad10afe
Revises: 031c20414986
Create Date: 2025-10-08 10:43:31.128758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c5aad10afe'
down_revision = '031c20414986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('authenticator_attachment')
        batch_op.drop_column('user_verification')
        batch_op.drop_column('mfa_required')
        batch_op.drop_column('password_history')
        batch_op.drop_column('lockout_duration')
        batch_op.drop_column('min_password_strength')
        batch_op.drop_column('password_expiry')
        batch_op.drop_column('auth_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password_expiry', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('min_password_strength', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lockout_duration', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password_history', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mfa_required', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_verification', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('authenticator_attachment', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
