"""add_password_policy_settings

Revision ID: 448723cc62fc
Revises: 29c5aad10afe
Create Date: 2025-10-08 11:04:05.126751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448723cc62fc'
down_revision = '29c5aad10afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add columns as nullable
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_password_length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('require_uppercase', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('require_lowercase', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('require_numbers', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('require_special_chars', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('password_expiry_days', sa.Integer(), nullable=True))

    # Update existing records with default values
    op.execute("UPDATE app_settings SET min_password_length = 8 WHERE min_password_length IS NULL")
    op.execute("UPDATE app_settings SET require_uppercase = true WHERE require_uppercase IS NULL")
    op.execute("UPDATE app_settings SET require_lowercase = true WHERE require_lowercase IS NULL")
    op.execute("UPDATE app_settings SET require_numbers = true WHERE require_numbers IS NULL")
    op.execute("UPDATE app_settings SET require_special_chars = true WHERE require_special_chars IS NULL")
    op.execute("UPDATE app_settings SET password_expiry_days = 90 WHERE password_expiry_days IS NULL")

    # Now alter columns to be NOT NULL
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('min_password_length', nullable=False)
        batch_op.alter_column('require_uppercase', nullable=False)
        batch_op.alter_column('require_lowercase', nullable=False)
        batch_op.alter_column('require_numbers', nullable=False)
        batch_op.alter_column('require_special_chars', nullable=False)
        batch_op.alter_column('password_expiry_days', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('password_expiry_days')
        batch_op.drop_column('require_special_chars')
        batch_op.drop_column('require_numbers')
        batch_op.drop_column('require_lowercase')
        batch_op.drop_column('require_uppercase')
        batch_op.drop_column('min_password_length')

    # ### end Alembic commands ###
