"""Allow NULL credential_id in SecurityKey

Revision ID: 68336fb44791
Revises: cf3316b2e6c4
Create Date: 2025-05-14 20:41:33.371799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68336fb44791'
down_revision = 'cf3316b2e6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_key', schema=None) as batch_op:
        batch_op.alter_column('credential_id',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('public_key',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_key', schema=None) as batch_op:
        batch_op.alter_column('public_key',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('credential_id',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
