"""Update unlocked_by column in Users table to store username and preserve failed attempts on unlock

Revision ID: 8639fffff42a
Revises: 
Create Date: 2025-05-20 22:28:16.867349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8639fffff42a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Then, alter the column type
        batch_op.alter_column('unlocked_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_unlocked_by', 'users', ['unlocked_by'], ['id'])
        batch_op.alter_column('unlocked_by',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
