"""Add SystemStatus and SystemConfiguration models

Revision ID: df120e2a3b2b
Revises: b1a2c3d4e5f6
Create Date: 2025-07-03 19:11:01.880600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df120e2a3b2b'
down_revision = 'b1a2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentication_session', schema=None) as batch_op:
        batch_op.drop_column('authentication_level')

    with op.batch_alter_table('system_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['updated_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configuration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('maintenance_message')

    with op.batch_alter_table('authentication_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authentication_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
