"""add_created_at_to_users

Revision ID: f622fdbbf79d
Revises: 448723cc62fc
Create Date: 2025-10-08 11:58:29.021943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f622fdbbf79d'
down_revision = '448723cc62fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # Set default values for existing users (use current timestamp)
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
